### ISSUE TITLE
似乎已经无法使用了

### ISSUE THREAD

**Issue by xiaotianxt** [ttttmr/Caiyun#11]
![image](https://user-images.githubusercontent.com/17041194/144232972-3673ec48-440b-4926-9fdd-c94377b83071.png)

**Comment by ttttmr** [comment]
我天天在用啊，有问题肯定第一时间发现，没见过这个报错

用这个版本最好不要登陆，并卸载官方插件

**Comment by GoTop** [comment]
1.2.7版的crx，安装之后无法启用

**Comment by ttttmr** [comment]
> 1.2.7版的crx，安装之后无法启用

年后看看，可以贴下无法使用提示了什么

**Comment by ttttmr** [comment]
> 1.2.7版的crx，安装之后无法启用

我可以正常用啊
退出彩云登陆，删除浏览器cookie、缓存，再试试
