### ISSUE TITLE
Can't work normally on Chorme

### ISSUE THREAD

**Issue by popsee** [ttttmr/Caiyun#16]
In 360 se browser ,this crx plugin is work well. That's very nice.
But why it state on innormal on chorme, my chrome version is  99.0.4844.51（X64）
![image](https://user-images.githubusercontent.com/13653691/158024530-a28fb80e-5268-4bb4-b7d0-5fcd7418ff69.png)
It can't work even thougt i clicked the fixed button.
what should i config if i want use this crx on chorme as well!
Please do me a favour and thank you so much!
sincerly yours!

**Comment by ttttmr** [comment]
Please read the readme carefully

> If you are **using Chrome**, you need to install it manually
>
> 1. download `crx` file and unzip
> 2. enable chrome extension developer mode
> 3. load unpacked extension
> 4. select the dir

**Comment by popsee** [comment]
Well. Thanks a lot/Just a little strange, the wrong icon is still keeping there,
![image](https://user-images.githubusercontent.com/13653691/158047725-0d95eb40-e461-4e5f-9dff-7e6b12612b65.png)
Even thougt there is something wrong, but fortunatelly i can use it, it worked@! it would be so nice!
Good fellow!

**Comment by ttttmr** [comment]
This is a known issue (the original extension plugin itself), I don't plan to deal with it, because it does not affect the use
