### ISSUE TITLE
 This extension may have been corrupted.

### ISSUE THREAD

**Issue by sahsu** [ttttmr/Caiyun#2]
seems newest chrome block this ext?

i will see  This extension may have been corrupted. for newest release ( caiyun-v1.1.6-fix2.crx )

**Comment by ttttmr** [comment]
Chrome needs to be installed manually, the crx version cannot be used

https://github.com/ttttmr/Caiyun#manual

**Comment by sahsu** [comment]
seems okay to me, closed.
