### ISSUE TITLE
抱歉，網頁認證有誤，請刷新重試

### ISSUE THREAD

**Issue by sahsu** [ttttmr/Caiyun#22]
When I trigger latest version I will see "抱歉，網頁認證有誤，請刷新重試" in Chrome, I tested with two different chrome account.

Can you check?

**Comment by ttttmr** [comment]
How to reproduce it, do you have screenshots?
I use it fine in my chrome

**Comment by sahsu** [comment]
Hi, I re-try today everything went to fine, I will close this.
