### ISSUE TITLE
手动安装后插件抛错，不能运行

### ISSUE THREAD

**Issue by treadpit** [ttttmr/Caiyun#3]
![image](https://user-images.githubusercontent.com/10692855/99341638-39e66180-28c5-11eb-872b-6ab3f2adb26a.png)

![image](https://user-images.githubusercontent.com/10692855/99341544-0efc0d80-28c5-11eb-959a-281740626823.png)

**Comment by ttttmr** [comment]
虽然报错了，但能用，所以一直没发现hh

**Comment by treadpit** [comment]
🤣 Good
