### ISSUE TITLE
还是有次数限制

### ISSUE THREAD

**Issue by 00LT00** [ttttmr/Caiyun#6]
不知道是不是那边更新了，现在还会弹窗提示我说次数不够

**Comment by ttttmr** [comment]
一直都是次数不够吗，我用着没啥问题
你是登陆了吗（不知道这魔改了还能不能登陆，我也没试过）

**Comment by 00LT00** [comment]
母鸡啊，我是安装了原版的，原版好像是登陆了，然后我把原版关了又安装的这个，我现在把官方版的卸了，又重装了下你这个，暂时能用了，不知道还有没有限制了

**Comment by 00LT00** [comment]
卸载官方版，删除cookie后正常
