### ISSUE TITLE
[Bug]在播放Youtube播放清单上的影片时会不断重新载入网页

### ISSUE THREAD

**Issue by Yusei-StarDust** [ttttmr/Caiyun#8]
如题，如果不是在播放清单中播放影片倒是正常，如果可以的话请修复这个问题，谢谢。

**Comment by ttttmr** [comment]
进入稍后观看，点开其中一个视频，没有复现

需要详细复现步骤

**Comment by Yusei-StarDust** [comment]
假设点进这个这个[播放清单](https://www.youtube.com/playlist?list=PLxs14g8zJsqB9TRJFTPo5V3hiSMpwbr2V)的页面：
![image](https://user-images.githubusercontent.com/26076608/126664426-eaca6192-4038-4127-83ea-645ef994b5d6.png)
然后点选第一个影片播放，影片会一直重新加载

https://user-images.githubusercontent.com/26076608/126669217-6a3c31c1-8202-4d60-aca2-6d54f57ef3e1.mp4



不过奇怪的是如果直接複製[影片开启后的网址](https://www.youtube.com/watch?v=8F1FrchMw5w&list=PLxs14g8zJsqB9TRJFTPo5V3hiSMpwbr2V&index=19)並將之贴上在新分页的网址列，然后Enter後：
![image](https://user-images.githubusercontent.com/26076608/126666457-b8b2c139-80d9-4429-abf4-7bc876fe0c01.png)
就不会有一直加载的Bug了，真是怪哉！

https://user-images.githubusercontent.com/26076608/126669038-63b9d50a-9f7f-478e-9c85-1e85c0114e39.mp4

**Comment by ttttmr** [comment]
确实有点奇怪，不太好排查，目前感觉是官方扩展的问题

晚点看看官方最新版有没有问题，如果没有的可以考虑升一下版本修hh

**Comment by ttttmr** [comment]
更新了，没这个bug了

**Comment by Yusei-StarDust** [comment]
非常感谢！
